
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

dispatch:
  - macro_namespace: dbt
    search_order: ['snowplow_utils', 'dbt']

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  snowplow_unified:
    # Configuration: https://docs.snowplow.io/docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/unified/
    snowplow__atomic_schema: aws_atomic_stream
    snowplow__events: 'events'
    snowplow__start_date: '2025-04-13'
    snowplow__enable_yauaa: true
    snowplow__enable_iab: false
    snowplow__derived_tstamp_partitioned: true
    snowplow__min_visit_length: 5 # Default is 10
    snowplow__heartbeat: 15 # Default is 10
    snowplow__backfill_limit_days: 30
    snowplow__app_id: ['NickDemo']
    snowplow__session_timestamp: 'load_tstamp'
    snowplow__enable_mobile: false
    snowplow__enable_web: true
    snowplow__enable_conversions: true
    snowplow__conversion_events: [
      {
        "name": "transaction", # Required, name of the conversion, string (must be valid SQL column name)
        "condition": " event_name = 'snowplow_ecommerce_action' and unstruct_event_com_snowplowanalytics_snowplow_ecommerce_snowplow_ecommerce_action_1.type = 'transaction' ", # Required, valid SQL condition that returns true or false
        "value": " 1 ", # Optional but recommended, can be field name or SQL
        "default_value": "0", # Optional, can be field name or SQL
        "list_events": "true" # Optional, boolean
      }
    ]
  snowplow_attribution:
    # Attribution Package configuration
    snowplow__start_date: '2025-04-13' # Required, the start date for conversions to be processed from.
    snowplow__attribution_list: ['first_touch', 'last_touch', 'linear', 'position_based'] # Optional, by default all are calculated
    snowplow__conversion_path_source: "{{ ref('snowplow_unified_views') }}"
    snowplow__conversions_source: "{{ ref('snowplow_unified_conversions') }}"
    snowplow__user_mapping_source: "{{ ref('snowplow_unified_user_mapping') }}"
  snowplow_ecommerce:
    snowplow__app_id: ['NickDemo']
    snowplow__disable_ecommerce_carts: true
    snowplow__disable_ecommerce_checkouts: true
    snowplow__disable_ecommerce_page_context: true
    snowplow__disable_ecommerce_transactions: true
    snowplow__disable_ecommerce_user_context: true
    snowplow__events_table: events
    snowplow__atomic_schema: aws_atomic_stream
    snowplow__derived_tstamp_partitioned: true
    snowplow__session_timestamp: 'load_tstamp'
    snowplow__start_date: '2025-04-13'




# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

#models:
#  snowplow_unified:
#    # Put all tables into the same schema defined in environment dataset section in dbt
#    +schema: null
#
#seeds:
#  snowplow_unified:
#    # Put all tables into the same schema defined in environment dataset section in dbt
#    +schema: null